// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpbdoqmkdlcaldlvwzsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwYmRvcW1rZGxjYWxkbHZ3enN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MDExODcsImV4cCI6MjA3Njk3NzE4N30.0XxvPm05D5ejHwnO5RNVsWCf5oti2Pr2AbMej_SXokk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});